### ISSUE TITLE
[Question] Backward pass with respect to the sparse matrix - dense or sparse?

### ISSUE THREAD

**Issue by tvercaut** [flaport/torch_sparse_solve#13]
Using the notation `x = A^{-1} b`, I am interested in the gradient with respect to sparse matrix `A` and more specifically the nonzero values in `A` but haven't been able to test the library yet (See #12 ).

I looked at the documentation but it wasn't clear to me whether the library would return a dense or a sparse matrix for `A.grad`. Reading [the blog post](https://blog.flaport.net/solving-sparse-linear-systems-in-pytorch.html) I can see the derivative with respect to the (dense matrix) being explained but the derivative with respect to only the non-zero values in `A` is not made explicit.

Does the libray support providing derivatives with repect to only the non-zero elements of A?

**Comment by flaport** [comment]
Indeed, the library only takes the nonzero elements into account.

**Comment by tvercaut** [comment]
Thanks. I'll close this "issue". It may be good to add a note about this in the main [readme](https://github.com/flaport/torch_sparse_solve#readme) of the repo.
