### ISSUE TITLE
Formulas in the backward

### ISSUE THREAD

**Issue by mpariente** [flaport/torch_sparse_solve#2]
Thanks for this great wrapper ! 

I wonder, could you point me towards formulas for `solve_backward` please?

https://github.com/flaport/torch_sparse_solve/blob/ce765cea780ab084e819048a77550c1129ccd878/torch_sparse_solve.cpp#L26-33

**Comment by flaport** [comment]
I derived those myself. 

Luckily I documented the process of making this library quite well and decided to make a little [blog post about it](https://blog.flaport.net/solving-sparse-linear-systems-in-pytorch.html), where I briefly go over the derivation.

**Comment by mpariente** [comment]
Youhou, it's my lucky day :tada: 

Thanks a lot !
