### ISSUE TITLE
Avoiding dense matmult

### ISSUE THREAD

**Issue by ladzin** [flaport/torch_sparse_solve#5]
Very nice library!

If I'm understanding your CPP code right, this line https://github.com/flaport/torch_sparse_solve/blob/ce765cea780ab084e819048a77550c1129ccd878/torch_sparse_solve.cpp#L28
is creating dense matrices, even though the result will later be sparsified. This wouldn't scale to large matrices that won't fit into memory dense; is there a way to compute just the nonzero elements?

**Comment by flaport** [comment]
Good point. A simple solution might be to just calculate the gradA for all COO-indices (i, j) of A. Something like this (in pseudo-code):

```
gradA[:,i,j] = sum(gradb[:,i,:]*x[:,j,:], -1)
```

I'm still a bit unsure what the influence on the performance might be. I'll try to implement and profile this once I find some time. However, feel free to try it out for yourself if you feel like it. PRs are always welcome 😉
