### ISSUE TITLE
Does torch_sparse_solve support backward propagation?

### ISSUE THREAD

**Issue by RodneyPerhaps** [flaport/torch_sparse_solve#6]
Hi, Floris!
Thank you for this amazing work! I just wonder if the solving process supports backward propagation?
Best regards, 
Rodney.

**Comment by flaport** [comment]
Hi @RodneyPerhaps , thanks for your kind words :)

yes, backward propagation is supported as can be seen [here](https://github.com/flaport/torch_sparse_solve/blob/master/torch_sparse_solve.py#L60).
